package com.vyms.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;

/**
 * Stores the computed payslip for one worker for one month.
 * Generated by SalaryCalculationService when the manager clicks "Generate
 * Payroll".
 */
@Entity
@Table(name = "payroll")
public class Payroll {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /** Payroll period — month (1-12) and year */
    private int month;
    private int year;

    /** Snapshot of employment type at generation time */
    private String employmentType;

    // ─── Phase 1: Base Pay ────────────────────────────────────────────────────
    /**
     * Raw base before deductions (basicSalary for PERMANENT; presentDays×dailyWage
     * for CONTRACT)
     */
    private BigDecimal basePay;

    /** Absent-day deduction for PERMANENT workers: (basicSalary/30) × absentDays */
    private BigDecimal leaveDeduction;

    /** Adjusted base = basePay - leaveDeduction */
    private BigDecimal adjustedBasePay;

    // ─── Attendance Summary ───────────────────────────────────────────────────
    private Integer presentDays;
    private Integer halfDays;
    private Integer absentDays;
    private Integer offDays;        // total OFF_DAY records in period
    private Integer unpaidOffDays;  // OFF_DAY beyond allowance (deducted for permanent workers)

    // ─── Phase 2: OT & Commission ─────────────────────────────────────────────
    /** Total OT hours across the period (hours beyond 8h/day) */
    private BigDecimal otHours;

    /** otHours × otHourlyRate */
    private BigDecimal otPay;

    /** Sales commission: sum of (salePrice × commissionRate / 100) in period */
    private BigDecimal commissionPay;

    /** adjustedBasePay + otPay + commissionPay */
    private BigDecimal grossSalary;

    // ─── Phase 3: EPF/ETF (PERMANENT only, else ZERO) ────────────────────────
    /** Employee EPF deduction: basicSalary × 0.08 */
    private BigDecimal epfEmployee;

    /** Company EPF contribution: basicSalary × 0.12 (not deducted from worker) */
    private BigDecimal companyEpf;

    /** Company ETF contribution: basicSalary × 0.03 (not deducted from worker) */
    private BigDecimal companyEtf;

    // ─── Phase 4: Net Salary ─────────────────────────────────────────────────
    /** grossSalary - epfEmployee */
    private BigDecimal netSalary;

    // ─── Getters / Setters ────────────────────────────────────────────────────
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public int getMonth() {
        return month;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public String getEmploymentType() {
        return employmentType;
    }

    public void setEmploymentType(String employmentType) {
        this.employmentType = employmentType;
    }

    public BigDecimal getBasePay() {
        return basePay;
    }

    public void setBasePay(BigDecimal basePay) {
        this.basePay = basePay;
    }

    public BigDecimal getLeaveDeduction() {
        return leaveDeduction;
    }

    public void setLeaveDeduction(BigDecimal leaveDeduction) {
        this.leaveDeduction = leaveDeduction;
    }

    public BigDecimal getAdjustedBasePay() {
        return adjustedBasePay;
    }

    public void setAdjustedBasePay(BigDecimal adjustedBasePay) {
        this.adjustedBasePay = adjustedBasePay;
    }

    public BigDecimal getOtHours() {
        return otHours;
    }

    public void setOtHours(BigDecimal otHours) {
        this.otHours = otHours;
    }

    public Integer getPresentDays() {
        return presentDays;
    }

    public void setPresentDays(Integer presentDays) {
        this.presentDays = presentDays;
    }

    public Integer getHalfDays() {
        return halfDays;
    }

    public void setHalfDays(Integer halfDays) {
        this.halfDays = halfDays;
    }

    public Integer getAbsentDays() {
        return absentDays;
    }

    public void setAbsentDays(Integer absentDays) {
        this.absentDays = absentDays;
    }

    public Integer getOffDays() {
        return offDays;
    }

    public void setOffDays(Integer offDays) {
        this.offDays = offDays;
    }

    public Integer getUnpaidOffDays() {
        return unpaidOffDays;
    }

    public void setUnpaidOffDays(Integer unpaidOffDays) {
        this.unpaidOffDays = unpaidOffDays;
    }

    public BigDecimal getOtPay() {
        return otPay;
    }

    public void setOtPay(BigDecimal otPay) {
        this.otPay = otPay;
    }

    public BigDecimal getCommissionPay() {
        return commissionPay;
    }

    public void setCommissionPay(BigDecimal commissionPay) {
        this.commissionPay = commissionPay;
    }

    public BigDecimal getGrossSalary() {
        return grossSalary;
    }

    public void setGrossSalary(BigDecimal grossSalary) {
        this.grossSalary = grossSalary;
    }

    public BigDecimal getEpfEmployee() {
        return epfEmployee;
    }

    public void setEpfEmployee(BigDecimal epfEmployee) {
        this.epfEmployee = epfEmployee;
    }

    public BigDecimal getCompanyEpf() {
        return companyEpf;
    }

    public void setCompanyEpf(BigDecimal companyEpf) {
        this.companyEpf = companyEpf;
    }

    public BigDecimal getCompanyEtf() {
        return companyEtf;
    }

    public void setCompanyEtf(BigDecimal companyEtf) {
        this.companyEtf = companyEtf;
    }

    public BigDecimal getNetSalary() {
        return netSalary;
    }

    public void setNetSalary(BigDecimal netSalary) {
        this.netSalary = netSalary;
    }

    // Convenience: total employer cost for this payslip
    public BigDecimal getEmployerCost() {
        BigDecimal epf = companyEpf != null ? companyEpf : BigDecimal.ZERO;
        BigDecimal etf = companyEtf != null ? companyEtf : BigDecimal.ZERO;
        BigDecimal net = netSalary != null ? netSalary : BigDecimal.ZERO;
        return net.add(epf).add(etf);
    }
}
